![Two data scientists working on a dashboard.](hr-image-small.png)

A common problem when creating models to generate business value from data is that the datasets can be so large that it can take days for the model to generate predictions. Ensuring that your dataset is stored as efficiently as possible is crucial for allowing these models to run on a more reasonable timescale without having to reduce the size of the dataset.

You've been hired by a major online data science training provider called *Training Data Ltd.* to clean up one of their largest customer datasets. This dataset will eventually be used to predict whether their students are looking for a new job or not, information that they will then use to direct them to prospective recruiters.

You've been given access to `customer_train.csv`, which is a subset of their entire customer dataset, so you can create a proof-of-concept of a much more efficient storage solution. The dataset contains anonymized student information, and whether they were looking for a new job or not during training:

| Column                   | Description                                                                      |
|------------------------- |--------------------------------------------------------------------------------- |
| `student_id`             | A unique ID for each student.                                                    |
| `city`                   | A code for the city the student lives in.                                        |
| `city_development_index` | A scaled development index for the city.                                         |
| `gender`                 | The student's gender.                                                            |
| `relevant_experience`    | An indicator of the student's work relevant experience.                          |
| `enrolled_university`    | The type of university course enrolled in (if any).                              |
| `education_level`        | The student's education level.                                                   |
| `major_discipline`       | The educational discipline of the student.                                       |
| `experience`             | The student's total work experience (in years).                                  |
| `company_size`           | The number of employees at the student's current employer.                       |
| `company_type`           | The type of company employing the student.                                       |
| `last_new_job`           | The number of years between the student's current and previous jobs.             |
| `training_hours`         | The number of hours of training completed.                                       |
| `job_change`             | An indicator of whether the student is looking for a new job (`1`) or not (`0`). |

In [487]:
# Import necessary libraries
import pandas as pd

# Load the dataset
ds_jobs = pd.read_csv("customer_train.csv")

# View the dataset
ds_jobs.head(10)

   student_id      city  ...  training_hours job_change
0        8949  city_103  ...              36        1.0
1       29725   city_40  ...              47        0.0
2       11561   city_21  ...              83        0.0
3       33241  city_115  ...              52        1.0
4         666  city_162  ...               8        0.0
5       21651  city_176  ...              24        1.0
6       28806  city_160  ...              24        0.0
7         402   city_46  ...              18        1.0
8       27107  city_103  ...              46        1.0
9         699  city_103  ...             123        0.0

[10 rows x 14 columns]

In [488]:
ds_jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  job_change              19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB

In [489]:
# Create a copy of ds_jobs for transforming
ds_jobs_transformed = ds_jobs.copy()

# Start coding here. Use as many cells as you like!

Columns containing categories with only two factors must be stored as Booleans (bool).
from what i can see gender, relevant_experience , enrolled_university, job_change are the ones with only boolean chances to be restructured

In [490]:
ds_jobs_transformed["gender"].value_counts() # Column discarteed?

Male      13221
Female     1238
Other       191
Name: gender, dtype: int64

In [491]:
ds_jobs_transformed["relevant_experience"].value_counts()

Has relevant experience    13792
No relevant experience      5366
Name: relevant_experience, dtype: int64

In [492]:
ds_jobs_transformed["enrolled_university"].value_counts() #column discarted

no_enrollment       13817
Full time course     3757
Part time course     1198
Name: enrolled_university, dtype: int64

In [493]:
ds_jobs_transformed["job_change"].value_counts()

0.0    14381
1.0     4777
Name: job_change, dtype: int64

So only job_change and relevant_experience are the ones that can take booleans conditions

In [494]:
ds_jobs_transformed["job_change"]=ds_jobs["job_change"].astype("bool")
ds_jobs_transformed["job_change"].dtype

dtype('bool')

In [495]:
ds_jobs_transformed["relevant_experience"]=ds_jobs["relevant_experience"].map({"Has relevant experience":True,"No relevant experience":False}).astype("bool")

Columns containing integers only must be stored as 32-bit integers (int32) applying .info we see that student_id, training_hours are the ones we must change

In [496]:
ds_jobs_transformed["student_id"] = ds_jobs["student_id"].astype("int32")
ds_jobs_transformed["training_hours"] = ds_jobs["training_hours"].astype("int32")

In [497]:
ds_jobs_transformed["city_development_index"] = ds_jobs["city_development_index"].astype("float16")

In [498]:
print(ds_jobs_transformed.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int32
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float16
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  bool
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int32
 13  job_change              19158 non-null  bool
dtypes: bool(2), float16(1), int32(2), object(9)
memory usage: 1.5+ MB
None

Columns containing nominal categorical data must be stored as the category data type.
education_level, major_discipline, enrolled_university, gender, company_type

In [499]:
ds_jobs_transformed.head()

   student_id      city  ...  training_hours job_change
0        8949  city_103  ...              36       True
1       29725   city_40  ...              47      False
2       11561   city_21  ...              83      False
3       33241  city_115  ...              52       True
4         666  city_162  ...               8      False

[5 rows x 14 columns]

In [500]:
ds_jobs_transformed["education_level"] = ds_jobs_transformed["education_level"].astype("category").cat.reorder_categories(new_categories = ['Primary School', 'High School','Graduate', 'Masters', 'Phd'], ordered = True)
ds_jobs_transformed["education_level"].dtype

CategoricalDtype(categories=['Primary School', 'High School', 'Graduate', 'Masters',
                  'Phd'],
, ordered=True)

In [501]:
ds_jobs_transformed["major_discipline"] = ds_jobs_transformed["major_discipline"].astype("category").cat.reorder_categories(new_categories=['No Major',"Arts", 'Business Degree', 'Humanities','STEM',"Other"],ordered=True)
ds_jobs_transformed["major_discipline"].dtype

CategoricalDtype(categories=['No Major', 'Arts', 'Business Degree', 'Humanities', 'STEM',
                  'Other'],
, ordered=True)

In [502]:
ds_jobs_transformed["enrolled_university"] = ds_jobs_transformed["enrolled_university"].astype("category").cat.reorder_categories(new_categories = ['no_enrollment', 'Part time course','Full time course'], ordered = True)
ds_jobs_transformed["enrolled_university"].dtype

CategoricalDtype(categories=['no_enrollment', 'Part time course', 'Full time course'], ordered=True)

In [503]:
ds_jobs_transformed["gender"] = ds_jobs_transformed["gender"].astype("category").cat.reorder_categories(new_categories = ['Female', 'Male', 'Other'], ordered = True)
ds_jobs_transformed["gender"].dtype

CategoricalDtype(categories=['Female', 'Male', 'Other'], ordered=True)

In [504]:
ds_jobs_transformed["company_type"] = ds_jobs_transformed["company_type"].astype("category").cat.reorder_categories(new_categories = ['Early Stage Startup', 'Funded Startup', 'Public Sector','NGO', 'Pvt Ltd','Other'], ordered = True)
ds_jobs_transformed["company_type"].dtype

CategoricalDtype(categories=['Early Stage Startup', 'Funded Startup', 'Public Sector',
                  'NGO', 'Pvt Ltd', 'Other'],
, ordered=True)

Columns containing ordinal categorical data must be stored as ordered categories, and not mapped to numerical values, with an order that reflects the natural order of the column.
 experience, company_size, last_new_job, city

For experience:

In [505]:
ds_jobs_transformed["experience"] = ds_jobs_transformed["experience"].astype("category") 
ds_jobs_transformed["experience"].cat.categories

Index(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2',
       '20', '3', '4', '5', '6', '7', '8', '9', '<1', '>20'],
      dtype='object')

In [506]:
ds_jobs_transformed["experience"] = ds_jobs_transformed["experience"].cat.reorder_categories(new_categories = ["<1" ,"1","2","3","4","5","6","7","8","9","10","11","12","13",'14',"15", "16", "17", "18", "19","20",">20"],ordered=True)
ds_jobs_transformed["experience"].cat.categories

Index(['<1', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '>20'],
      dtype='object')

For last_new_job:

In [507]:
ds_jobs_transformed["last_new_job"] = ds_jobs_transformed["last_new_job"].astype("category").cat.reorder_categories(new_categories = ['never','1', '2', '3', '4', '>4'],ordered=True)
ds_jobs_transformed["last_new_job"].cat.categories

Index(['never', '1', '2', '3', '4', '>4'], dtype='object')

For company_size:

In [508]:
ds_jobs_transformed["company_size"] = ds_jobs_transformed["company_size"].astype("category").cat.reorder_categories(new_categories = [ '<10','10-49','50-99', '100-499', '500-999','1000-4999', '5000-9999','10000+'],ordered=True)
ds_jobs_transformed["company_size"].cat.categories

Index(['<10', '10-49', '50-99', '100-499', '500-999', '1000-4999', '5000-9999',
       '10000+'],
      dtype='object')

For_city theres a problem, we might need to make a change so we can order it first then append teh word city::

In [509]:
ds_jobs_transformed["city"] = ds_jobs_transformed["city"].astype("category")
ds_jobs_transformed["city"].cat.categories

Index(['city_1', 'city_10', 'city_100', 'city_101', 'city_102', 'city_103',
       'city_104', 'city_105', 'city_106', 'city_107',
       ...
       'city_84', 'city_89', 'city_9', 'city_90', 'city_91', 'city_93',
       'city_94', 'city_97', 'city_98', 'city_99'],
      dtype='object', length=123)

As the categories do not follow a numerical order, we must rearrenge them, my first thought was to erase all str in the col and then append the str after we ordered it, but i thought of this solution

In [510]:
ordered_cats = ["city_" + str(i) for i in range(1, 124)] #As we know from the .info the number of cats, we make this range instead of searching through the DF

ds_jobs_transformed["city"] = pd.Categorical(ds_jobs_transformed["city"] ,categories=ordered_cats, ordered=True)
ds_jobs_transformed["city"].cat.categories

Index(['city_1', 'city_2', 'city_3', 'city_4', 'city_5', 'city_6', 'city_7',
       'city_8', 'city_9', 'city_10',
       ...
       'city_114', 'city_115', 'city_116', 'city_117', 'city_118', 'city_119',
       'city_120', 'city_121', 'city_122', 'city_123'],
      dtype='object', length=123)

The DataFrame should be filtered to only contain students with 10 or more years of experience at companies with at least 1000 employees, as their recruiter base is suited to more experienced professionals at enterprise companies.

In [511]:
ds_jobs_transformed["company_size"].cat.categories

Index(['<10', '10-49', '50-99', '100-499', '500-999', '1000-4999', '5000-9999',
       '10000+'],
      dtype='object')

In [512]:
ds_jobs_transformed["experience"].cat.categories

Index(['<1', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '>20'],
      dtype='object')

As them both are ORDERED categories we can use a comparative numerical expresion such as <=, if they werent we must go use .isin

In [513]:
ds_jobs_transformed = ds_jobs_transformed[
    (ds_jobs_transformed["experience"] >= "10") &
    (ds_jobs_transformed["company_size"] >= "1000-4999")
]

In [514]:
ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2201 entries, 9 to 19143
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              2201 non-null   int32
 1   city                    1964 non-null   category
 2   city_development_index  2201 non-null   float16
 3   gender                  1821 non-null   category
 4   relevant_experience     2201 non-null   bool
 5   enrolled_university     2185 non-null   category
 6   education_level         2184 non-null   category
 7   major_discipline        2097 non-null   category
 8   experience              2201 non-null   category
 9   company_size            2201 non-null   category
 10  company_type            2144 non-null   category
 11  last_new_job            2184 non-null   category
 12  training_hours          2201 non-null   int32
 13  job_change              2201 non-null   bool
dtypes: bool(2), category(9), float16(1), int32(2)
memory usage: 69.5 KB

In [515]:
ds_jobs_transformed.head()

    student_id      city  ...  training_hours job_change
9          699  city_103  ...             123      False
12       25619   city_61  ...              23      False
31       22293  city_103  ...             141      False
34       26494   city_16  ...             145      False
40        2547  city_114  ...              14      False

[5 rows x 14 columns]